<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationDefaultFont>Segoe UI, 9pt</ApplicationDefaultFont>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <AssemblyName>QrScan</AssemblyName>
    <RootNamespace>QrScan</RootNamespace>
    <DebugType Condition="'$(Configuration)'=='Release'">none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\QrScan.Core\QrScan.Core.csproj" />
  </ItemGroup>
</Project>
